// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXMT8W4Rv1CYFcPHwlq7cVpFhf1EMUpsM',
    appId: '1:616915865276:web:5485a3fbc174e952308ab9',
    messagingSenderId: '616915865276',
    projectId: 'basic-notification-bb342',
    authDomain: 'basic-notification-bb342.firebaseapp.com',
    storageBucket: 'basic-notification-bb342.appspot.com',
    measurementId: 'G-P18BSMJ0YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgywjWxCz11iaO4rGLXR10mvmBhJAGBOk',
    appId: '1:616915865276:android:de777a18694f503c308ab9',
    messagingSenderId: '616915865276',
    projectId: 'basic-notification-bb342',
    storageBucket: 'basic-notification-bb342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1R0O_en4PD8tIB5QwsIhmdeCHXvcAP-Q',
    appId: '1:616915865276:ios:dbd1ab8d094efed2308ab9',
    messagingSenderId: '616915865276',
    projectId: 'basic-notification-bb342',
    storageBucket: 'basic-notification-bb342.appspot.com',
    iosClientId: '616915865276-bpe6pdk6j3l3sp6cpkipsvmu48tc4g68.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1R0O_en4PD8tIB5QwsIhmdeCHXvcAP-Q',
    appId: '1:616915865276:ios:dbd1ab8d094efed2308ab9',
    messagingSenderId: '616915865276',
    projectId: 'basic-notification-bb342',
    storageBucket: 'basic-notification-bb342.appspot.com',
    iosClientId: '616915865276-bpe6pdk6j3l3sp6cpkipsvmu48tc4g68.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicNotification',
  );
}
